Added the profile image
Real-Dev-Squad/website-static pull request #122
Opened 2021-09-06 16:56 UTC by rohan09-raj

2021-09-06 17:35 UTC, Pavangbhat requested changes
Image is less than 500x500 pixels :smiley:

2021-09-06 17:39 UTC, rohan09-raj commented
> Image is less than 500x500 pixels and its good to have a better quality image 😃

I checked the reso

> Image is less than 500x500 pixels 😃

Ohh sorry, I checked it before committing it was 600×600, but I guess I checked the previous image, will correct it 😅

2021-09-06 18:45 UTC, Pavangbhat approved these changes
Looks good to me

2021-09-12 05:22 UTC, ankushdharkar approved these changes

2021-09-12 05:22 UTC, merged