Add Sujit
Real-Dev-Squad/website-static pull request #36
Opened 2020-09-16 18:50 UTC by sujitmohanty

Added sujit as a member

2020-09-16 18:53 UTC, ankushdharkar requested changes
- Alphabetic order not maintained
- Picture is not square
- Face does not cover > 60% of the image

2020-09-16 18:53 UTC, ankushdharkar commented on ids/mapping.json
> +  "sujit": "sujitmohanty"
Alphabetic order not maintained

2020-09-16 19:23 UTC, sujitmohanty reviewed
-Fixed order.
-Cropped Image to ensure it's a square and meets min. size requirements

2020-09-16 19:42 UTC, ankushdharkar requested changes
Why were 16 files changed? Please only push the code that pertains to your entry

2020-09-17 07:29 UTC, sujitmohanty reviewed
-Undid Prettier auto-formatting
-Re-fixed alphabetical order
-Changed Image

2020-10-10 14:35 UTC, swarajpure approved these changes
Looks good to me.

2020-10-10 14:37 UTC, merged