Feat(members): New member added
Real-Dev-Squad/website-static pull request #56
Opened 2020-11-26 18:10 UTC by SagarBajpai

New folder created with **sagar**
Contains img.png and data.json file.

2020-11-26 18:12 UTC, ankushdharkar requested changes
- Photo rules not followed
- mapping.json entry missing

2020-11-26 18:12 UTC, whyDontI requested changes
mapping.json entry is missing 🤣

2020-11-29 07:15 UTC, ankushdharkar approved these changes

2020-11-29 07:17 UTC, ankushdharkar approved these changes

2020-11-29 07:17 UTC, merged