Contribute/files
Real-Dev-Squad/website-static pull request #87
Opened 2021-02-28 22:24 UTC by DashDeipayan

2021-02-28 22:27 UTC, DashDeipayan commented
@ankushdharkar please review my changes. I've updated the CONTRIBUTING.md file and README.md file to serve the current state purposes up to my knowledge of appropriation.

2021-02-28 22:29 UTC, DashDeipayan commented on README.md
> -- Must maintain alphabetic order in the `mappings` file
As there is no file by the name `mappings` I found this redundant.

2021-03-01 02:42 UTC, ankushdharkar requested changes

2021-03-01 02:42 UTC, ankushdharkar commented on CONTRIBUTING.md
> +# Adding my profile picture for Members page
*your

2021-03-01 02:42 UTC, ankushdharkar commented on CONTRIBUTING.md
> +Add your RDS ID (you can choose any, if it doesn't exist before).
We don't choose an ID here anymore. This sentence can be removed, right?

2021-03-01 02:42 UTC, ankushdharkar commented on README.md
> +- Must be **unique**
This happens on the form now. Do we still need this here?

2021-03-01 02:42 UTC, ankushdharkar commented on README.md
> +- Image must be a `*.png`
`img.png` to be specific then

2021-03-01 03:08 UTC, DashDeipayan commented
I changed them accordingly. Kindly review the changes @ankushdharkar

2021-03-03 11:48 UTC, swarajpure commented on CONTRIBUTING.md
> +- Add your personal details in this repository by signing in on our [website](https://www.realdevsquad.com) so that it appears on the [members](https://members.realdevsquad.com/) page.
Umm... When a user signs in on this website, only the user's `github_id` and `github_display_name` (if any) are stored in the database.
For users to be able to fill their personal details (first name, last name, username, company etc), we have got https://my.realdevsquad.com/signup
This form is the place where users can fill in their personal details which are required to be displayed on the members page

First the users will sign in via github on realdevsquad.com and then they should go to https://my.realdevsquad.com/signup to fill their profile

2021-03-03 11:48 UTC, swarajpure commented on CONTRIBUTING.md
> +Make a new folder using your unique **RDS ID** in `members` folder.
Can we call this **RDS username** instead?

2021-03-03 16:04 UTC, DashDeipayan commented
I have made the modifications according to the reviews. @swarajpure @ankushdharkar please review this PR.

2021-03-10 19:49 UTC, swarajpure approved these changes
Looks good to me.
Thanks!

2021-03-13 20:43 UTC, merged